### PR TITLE
Fix Committee Head Responsive Design (#224)

### LINKED ISSUE #224: Bug: Committee Heads Styling Not Following Responsive Design
**Describe the bug**
The committee heads div section is not following responsive design, unlike the primary officer counterpart. This causes weird styling to occur when viewing from a mobile display, making it undesirable. 

**To Reproduce**
1. Visit Leadership Page on a screen that is vertically oriented. 

**Expected behavior**
It should stay centered and flex with the screen so that styling stays consistent and is readable.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - Browser: Google Chrome (Responsive Design Mode on Computer)

### PR DESCRIPTION
**Pull request by Phoenixxo**
This PR is set to fix the Committee Head div not properly displaying when on a device that is vertically oriented (mobile device). Fixes #224

### CODE REVIEW

File: next/app/about/leadership/page.tsx [hunk 1]
```diff
@@ -121,7 +121,7 @@ export default function Leadership() {
 						<h2 className="text-xl text-center font-extrabold text-primary-focus sm:text-3xl my-12">
 							Committee Heads
 						</h2>
-						<div className="mt-5">
+						<div className="w-full flex flex-row justify-center space-x-5">
```
Comment (2nPlusOne) [inline next/app/about/leadership/page.tsx:124]: I'd use `gap` here instead of space-x to utilize the native flexbox gap feature instead of margin. All browsers support it now.

**Review by 2nPlusOne — COMMENTED** [review]
👍

File: next/app/about/leadership/page.tsx (hunk 1 above)
Comment (Phoenixxo) [reply next/app/about/leadership/page.tsx]: Added 👍

**Comment by pybash** [comment]
LGTM! 🚀
