### PR TITLE
Dev/unified auth gateway

### LINKED ISSUE #324: Standardize mentor identifier naming across API (mentorId vs mentor_Id)
sometimes we use mentorid and sometimes we use mentor_id. non-blocking nit. feel free to resolve without actually resolving and make an issue

_Originally posted by @jjalangtry in https://github.com/rit-sse/WebsiteTheSSEquel/pull/322#discussion_r2824861145_
            
We currently use mixed naming for mentor identifiers in API contracts and payloads (mentorId, mentor_Id, occasionally references to mentor_id in comments/discussion). This creates avoidable confusion.

### Acceptance Critiera

- [ ] Single canonical external field name (mentorId) across APIs.
- [ ] No behavior regressions for existing clients during migration window.
- [ ]  Updated API docs/tests to match canonical naming.

### PR DESCRIPTION
**Pull request by Phoenixxo**
- Add staging environment auth so that devs can easily QA without worrying about having to manually get auth themselves
- Unify the Auth Gateways across APIs to keep apis more secure and consistent

Reopened 02/19/26

Closes #324 #323

### CODE REVIEW

File: next/app/api/event/[id]/attendance/route.ts [hunk 1]
```diff
@@ -1,18 +1,18 @@
...
-import { NextRequest, NextResponse } from "next/server";
+import {NextRequest, NextResponse} from "next/server";
+import {getGatewayAuthLevel} from "@/lib/authGateway";
 
 /**
  * Helper function to get user from session token
  */
 async function getUserFromSession(request: NextRequest) {
-  const authToken = getSessionToken(request);
+  const authToken = request.cookies.get(process.env.SESSION_COOKIE_NAME!)?.value;
```
Comment (jjalangtry) [inline next/app/api/event/[id]/attendance/route.ts]: shouldnt we get all of these things from helpers and not directly from the cookies? id like to see no new request.cookies.get if we have the infrastructure to not use direct calls.

non blocking can be made an issue
